version: '3.8'

services:
  vinted-notifications:
    image: fuyucch1/vinted-notifications:latest
    pull_policy: always
    ports:
      - "18472:18472"
      - "18473:18473"
    volumes:
      - VN_data:/app/data
      - VN_logs:/app/logs
    restart: unless-stopped
    read_only: true
    tmpfs:
      - /tmp

volumes:
  VN_data:
  VN_logs:
